# Generated by Django 4.2.1 on 2023-08-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_extention',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
