# Generated by Django 4.2.1 on 2023-07-05 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='شماره تلفن'),
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='گرایش')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maghta', models.CharField(blank=True, choices=[('arshad', 'ارشد'), ('doctora', 'دکتری')], default='arshad', max_length=7, verbose_name='مقطع')),
                ('student_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره دانشجویی')),
                ('is_student', models.BooleanField(default=True, verbose_name='دانشجو است')),
                ('is_prof', models.BooleanField(default=False, verbose_name='استاد است')),
                ('proposal_name', models.CharField(max_length=1500)),
                ('study_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studyfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
