# Generated by Django 4.2.1 on 2023-08-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_user_phone_number_studyfield_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_prof',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='proposal_name',
        ),
        migrations.AddField(
            model_name='user',
            name='is_prof',
            field=models.BooleanField(default=False, verbose_name='استاد است'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='دانشجو است'),
        ),
    ]
