# Generated by Django 4.2.1 on 2023-08-28 16:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import panel.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=panel.utils.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('بررسی توسط استاد راهنما', 'بررسی توسط استاد راهنما'), ('در انتظار تعیین ارزیاب', 'در انتظار تعیین ارزیاب'), ('در حال ارزیابی', 'در حال ارزیابی'), ('رد شده', 'رد شده'), ('تصویب شده', 'تصویب شده')], default='بررسی توسط استاد راهنما', max_length=50, verbose_name='وضعیت')),
                ('name', models.CharField(default='', max_length=1500)),
                ('extention', models.CharField(default='', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_owner', to=settings.AUTH_USER_MODEL)),
                ('prof_moshaver', models.ForeignKey(limit_choices_to={'is_prof': True}, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_profs_moshaver', to=settings.AUTH_USER_MODEL)),
                ('prof_rahnama', models.ForeignKey(limit_choices_to={'is_prof': True}, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_profs_rahnama', to=settings.AUTH_USER_MODEL)),
                ('profs_arzyab', models.ManyToManyField(blank=True, limit_choices_to={'is_prof': True}, related_name='proposal_profs_arzyab', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
