# Generated by Django 4.2.1 on 2023-08-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='date_edited',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_added',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='prof_moshaver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_prof': True}, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_profs_moshaver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='prof_rahnama',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_prof': True}, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_profs_rahnama', to=settings.AUTH_USER_MODEL),
        ),
    ]
