# Generated by Django 4.2.1 on 2023-08-29 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0005_alter_proposal_prof_moshaver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='prof_moshaver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_prof': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_profs_moshaver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='prof_rahnama',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_prof': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_profs_rahnama', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='profs_arzyab',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_prof': True}, related_name='proposal_profs_arzyab', to=settings.AUTH_USER_MODEL),
        ),
    ]
