# Generated by Django 4.2.1 on 2023-08-29 09:03

import django.core.validators
from django.db import migrations, models
import panel.utils


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_proposal_prof_moshaver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='hamanand_juii_file',
            field=models.FileField(blank=True, null=True, upload_to=panel.utils.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='proposal',
            name='irandoc_file',
            field=models.FileField(blank=True, null=True, upload_to=panel.utils.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
