# Generated by Django 4.2.1 on 2023-08-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_proposal_hamanand_juii_file_proposal_irandoc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('هنوز درخواست تصویب داده نشده', 'هنوز درخواست تصویب داده نشده'), ('در حال تصویب', 'در حال تصویب'), ('تصویب شده', 'تصویب شده'), ('رد شده', 'رد شده')], default='هنوز درخواست تصویب داده نشده', max_length=50, verbose_name='وضعیت'),
        ),
    ]
