# Generated by Django 4.2.1 on 2023-08-29 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import panel.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0008_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='prof_moshaver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_prof': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_moshaver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='prof_rahnama',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_prof': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_rahnama', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='profs_arzyab',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_prof': True}, related_name='proposals_arzyab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=panel.utils.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('date_added', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('date_edited', django_jalali.db.models.jDateField(auto_now=True)),
                ('name', models.CharField(default='', max_length=1500)),
                ('extention', models.CharField(default='', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissertations_owner', to=settings.AUTH_USER_MODEL)),
                ('prof_moshaver', models.ForeignKey(blank=True, limit_choices_to={'is_prof': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dissertations_moshaver', to=settings.AUTH_USER_MODEL)),
                ('prof_rahnama', models.ForeignKey(blank=True, limit_choices_to={'is_prof': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dissertations_rahnama', to=settings.AUTH_USER_MODEL)),
                ('profs_arzyab', models.ManyToManyField(blank=True, limit_choices_to={'is_prof': True}, related_name='dissertations_arzyab', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
