# Generated by Django 4.2.1 on 2023-08-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_alter_proposal_owner_alter_proposal_prof_moshaver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='moshaver_one_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moshaver_two_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rahnama_one_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rahnama_two_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('هنوز درخواست تصویب داده نشده', 'هنوز درخواست تصویب داده نشده'), ('در انتظار تأیید استاد راهنما', 'در انتظار تأیید استاد راهنما'), ('در انتظار تأیید استاد مشاور', 'در انتظار تأیید استاد مشاور'), ('در انتظار تأیید استاد ارزیاب', 'در انتظار تأیید استاد ارزیاب'), ('در انتظار تأیید مدیر گروه', 'در انتظار تأیید مدیر گروه'), ('تصویب شده', 'تصویب شده'), ('رد شده', 'رد شده')], default='هنوز درخواست تصویب داده نشده', max_length=50, verbose_name='وضعیت'),
        ),
    ]
